build:
	sudo docker build -t camilocartagena/ubuntu-java11 .
cli:
	sudo docker run -i -t camilocartagena/ubuntu-java11
remove:
	../remove_container.sh camilocartagena/ubuntu-java11
push:
	sudo docker push camilocartagena/ubuntu-java11
pull:
	sudo docker pull camilocartagena/ubuntu-java11
list:
	sudo docker images